import React, { useState } from "react";
import {Button} from "react-bootstrap";

function Registration_birthday(props) {
  const [val, setVal] = useState([]);

  const handleChange = (e) => {

    if (val.includes(e.target.value)) {

      setVal(val.filter((item) => item !== e.target.value));
    } else {
      setVal([...val, e.target.value]);
    }

    props.setTaglist(val)
  };

  return (
    <div class="container">
      <div class="row">
        <div class="col-sm-3 col-xs-6">
          <>
            <div>
              <label>
                <input
                  type="checkbox"
                  value= "1"
                  checked={val.includes("1")}
                  onChange={handleChange}
                />
                レディースファッション
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="2"
                  checked={val.includes("2")}
                  onChange={handleChange}
                />
                メンズファッション
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="3"
                  checked={val.includes("3")}
                  onChange={handleChange}
                />
                インナー・下着・ナイトウェア
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="4"
                  checked={val.includes("4")}
                  onChange={handleChange}
                />
                バッグ・小物・ブランド雑貨
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="5"
                  checked={val.includes("5")}
                  onChange={handleChange}
                />
                靴
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="6"
                  checked={val.includes("6")}
                  onChange={handleChange}
                />
                腕時計
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="7"
                  checked={val.includes("7")}
                  onChange={handleChange}
                />
                ジュエリー・アクセサリー
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="8"
                  checked={val.includes("8")}
                  onChange={handleChange}
                />
                キッズ・ベビー・マタニティ
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="9"
                  checked={val.includes("9")}
                  onChange={handleChange}
                />
                おもちゃ
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="10"
                  checked={val.includes("10")}
                  onChange={handleChange}
                />
                スポーツ・アウトドア
              </label>
            </div>
          </>
        </div>
        <div class="col-sm-3 col-xs-6">
          <>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="11"
                  onChange={handleChange}
                  
                />
                家電
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="12"
                  onChange={handleChange}
                  checked={val.includes("12")}
                />
                TV・オーディオ・カメラ
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="13"
                  onChange={handleChange}
                  checked={val.includes("13")}
                />
                パソコン・周辺機器
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="14"
                  onChange={handleChange}
                  checked={val.includes("14")}
                />
                スマートフォン・タブレット
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="15"
                  onChange={handleChange}
                  checked={val.includes("15")}
                />
                光回線・モバイル通信
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="16"
                  onChange={handleChange}
                  checked={val.includes("16")}
                />
                食品
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="17"
                  onChange={handleChange}
                  checked={val.includes("17")}
                />
                スイーツ・お菓子
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="18"
                  onChange={handleChange}
                  checked={val.includes("18")}
                />
                水・ソフトドリンク
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="19"
                  onChange={handleChange}
                  checked={val.includes("19")}
                />
                ビール・洋酒
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="20"
                  onChange={handleChange}
                  checked={val.includes("20")}
                />
                日本酒・焼酎
              </label>
            </div>
          </>
        </div>
        <div class="col-sm-3 col-xs-6">
          <>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="21"
                  onChange={handleChange}
                  checked={val.includes("21")}
                />
                インテリア・寝具・収納
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="22"
                  onChange={handleChange}
                  checked={val.includes("22")}
                />
                日用品雑貨・文房具・手芸
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="23"
                  onChange={handleChange}
                  checked={val.includes("23")}
                />
                キッチン用品・食器・調理器具
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="24"
                  onChange={handleChange}
                  checked={val.includes("24")}
                />
                本・雑誌・コミック
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="25"
                  onChange={handleChange}
                  checked={val.includes("25")}
                />
                CD・DVD
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="26"
                  onChange={handleChange}
                  checked={val.includes("26")}
                />
                テレビゲーム
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="27"
                  onChange={handleChange}
                  checked={val.includes("27")}
                />
                ホビー
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="28"
                  onChange={handleChange}
                  checked={val.includes("28")}
                />
                楽器・音響機器
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="29"
                  onChange={handleChange}
                  checked={val.includes("29")}
                />
                車・バイク
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="30"
                  onChange={handleChange}
                  checked={val.includes("30")}
                />
                車用品・バイク用品
              </label>
            </div>
          </>
        </div>
        <div class="col-sm-3 col-xs-6">
          <>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="31"
                  onChange={handleChange}
                  checked={val.includes("31")}
                />
                美容・コスメ・香水
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="32"
                  onChange={handleChange}
                  checked={val.includes("32")}
                />
                ダイエット・健康
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="33"
                  onChange={handleChange}
                  checked={val.includes("33")}
                />
                医薬品・コンタクト・介護
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="34"
                  onChange={handleChange}
                  checked={val.includes("34")}
                />
                ペット・ペットグッズ
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="35"
                  onChange={handleChange}
                  checked={val.includes("35")}
                />
                花・ガーデン・DIY
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="36"
                  onChange={handleChange}
                  checked={val.includes("36")}
                />
                サービス・リフォーム
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="37"
                  onChange={handleChange}
                  checked={val.includes("37")}
                />
                住宅・不動産
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="38"
                  onChange={handleChange}
                  checked={val.includes("38")}
                />
                カタログギフト・チケット
              </label>
            </div>
            <div>
              <label>
                <input
                  type="checkbox"
                  value="39"
                  onChange={handleChange}
                  checked={val.includes("39")}
                />
                百貨店・総合通販・ギフト
              </label>
            </div>
          </>
        </div>
      </div>
      <Button onClick={handleChange}>
        Conifrm
      </Button>
    </div>
  );
}

export default Registration_birthday;
